version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
    timezone: Europe/London
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: rubocop
    versions:
    - 1.10.0
    - 1.11.0
    - 1.12.0
    - 1.9.0
  - dependency-name: bundler
    versions:
    - 2.2.7
    - 2.2.8
  - dependency-name: faraday
    versions:
    - 1.3.0
