AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.4

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - '*.gemspec'

Metrics/LineLength:
  Exclude:
    - '*.gemspec'

inherit_from: .rubocop_todo.yml
