AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.6.0

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - '*.gemspec'

Layout/LineLength:
  Exclude:
    - '*.gemspec'

inherit_from: .rubocop_todo.yml
