sudo: false
language: ruby
rvm:
  - 2.6.0
  - 2.6.1
  - 2.6.2
  - 2.6.3
  - 2.6.4
  - 2.6.5
  - 2.6.6
  - 2.7.0
before_install:
  - gem update --system
  - gem install bundler -v 2.2.8
script:
  - bundle exec rubocop -v
  - bundle exec rake
