sudo: false
language: ruby
rvm:
  - 2.5.5
  - 2.6.0
  - 2.6.1
  - 2.6.2
  - 2.6.3
before_install:
  - gem update --system
  - gem install bundler -v 2.1.2
script:
  - bundle exec rubocop -v
  - bundle exec rake
