sudo: false
language: ruby
rvm:
  - 2.6.6
  - 2.7.0
  - 2.7.1
  - 2.7.2
before_install:
  - gem update --system
  - gem install bundler -v 2.2.8
script:
  - bundle exec rubocop -v
  - bundle exec rake
